package br.com.depro.mugetsu.carga.anime.model;

import br.com.depro.mugetsu.model.media.util.FormatoAnime;
import br.com.depro.mugetsu.model.media.util.FormatoDorama;
import br.com.depro.mugetsu.model.media.util.FormatoMedia;

/**
 * @author rsouza
 */
public enum FormatoANN {
                            
	TV 				        (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV1978 			        (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV1989 			        (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV2      		        (FormatoMedia.ANIME, FormatoAnime.TV, null),
	U_S_TV 			        (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV13                    (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV14                    (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV15                    (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV16                    (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV10                    (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV21992                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV11                    (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV12                    (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV11998                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV17                    (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV18                    (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV19                    (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV21987                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV21985                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV21983                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV21980                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV11984                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV1                     (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV21989                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV3                     (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV5                     (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV4                     (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV7                     (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV6                     (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV9                     (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV8                     (FormatoMedia.ANIME, FormatoAnime.TV, null),
	cancelledTV             (FormatoMedia.ANIME, FormatoAnime.TV, null),
	clayanimationTV         (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV76                    (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV75                    (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV1968                  (FormatoMedia.ANIME, FormatoAnime.TV, null),
	liveactionTV            (FormatoMedia.ANIME, FormatoAnime.TV, null),
	KBSToeiTV               (FormatoMedia.ANIME, FormatoAnime.TV, null),
	U_S_TVpromo             (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV20                    (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV12002                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV92                    (FormatoMedia.ANIME, FormatoAnime.TV, null),
	USTV                    (FormatoMedia.ANIME, FormatoAnime.TV, null),
	DramaCDTVsidestory      (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV2011                  (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV311988                (FormatoMedia.ANIME, FormatoAnime.TV, null),
	KoreanTV                (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV22009                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV22006                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV22005                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TVPromo                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV2005                  (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV2007                  (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV1975                  (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV22000                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV2009                  (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV2008                  (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV11973                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV11972                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV31985                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV11976                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV52007                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV21979                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TVorOAVormovie          (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV21971                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV2009renewal           (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV11966                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV41996                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV11965                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV11963                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV32003                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV11968                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV11967                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV32005                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TVpromo                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	puppetshowTV            (FormatoMedia.ANIME, FormatoAnime.TV, null),
	stalledTV               (FormatoMedia.ANIME, FormatoAnime.TV, null),
	puppetTV                (FormatoMedia.ANIME, FormatoAnime.TV, null),	
	TV2013                  (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV22013                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV2012                  (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV22001                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	U_S_                    (FormatoMedia.ANIME, FormatoAnime.TV, null),
	HongKongTV              (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV32014                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV32015                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV2015                  (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV22014                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV22016                 (FormatoMedia.ANIME, FormatoAnime.TV, null),
	TV1977					(FormatoMedia.ANIME, FormatoAnime.TV, null),
	
	
	OAV 			        (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	amateurOAV 		        (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAV11988                (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAV32003                (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	ONA2                    (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAVbyHitoshiKino        (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAV1                    (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAV3                    (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAV2                    (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAV11992                (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAV1987                 (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAV1986                 (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	U_S_OAVParody           (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAVbyUJin               (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAV1991                 (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAV1994                 (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAV1995                 (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	cancelledOAV            (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAV22012                (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	U_S_OAV                 (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	USIndependentOAV        (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAV2011                 (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAV21990                (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAVPromo                (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAV2003                 (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAV21994                (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAV2009                 (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	nonexistentOAV          (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	cancelledOAV3           (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	OAV2014                 (FormatoMedia.ANIME, FormatoAnime.OAV, null),
	novels					(FormatoMedia.ANIME, FormatoAnime.OAV, null),
	
	ONA 					(FormatoMedia.ANIME, FormatoAnime.ONA, null),
	KoreanONA               (FormatoMedia.ANIME, FormatoAnime.ONA, null),
	suspendedONA            (FormatoMedia.ANIME, FormatoAnime.ONA, null),
	mobilephoneONA          (FormatoMedia.ANIME, FormatoAnime.ONA, null),
	novel				    (FormatoMedia.ANIME, FormatoAnime.ONA, null),
	mook  				    (FormatoMedia.ANIME, FormatoAnime.ONA, null),
	musicalspecial          (FormatoMedia.ANIME, FormatoAnime.ONA, null),
	AprilfoolsJOKE          (FormatoMedia.ANIME, FormatoAnime.ONA, null),
	TVorOAV 			    (FormatoMedia.ANIME, FormatoAnime.ONA, null),
	ONA2014                 (FormatoMedia.ANIME, FormatoAnime.ONA, null),
	ONA2015                 (FormatoMedia.ANIME, FormatoAnime.ONA, null),
	U_S_ONA					(FormatoMedia.ANIME, FormatoAnime.ONA, null),
	
	specials                (FormatoMedia.ANIME, FormatoAnime.ESPECIAL, null),
	special2                (FormatoMedia.ANIME, FormatoAnime.ESPECIAL, null),
	special1986             (FormatoMedia.ANIME, FormatoAnime.ESPECIAL, null),
	special1980             (FormatoMedia.ANIME, FormatoAnime.ESPECIAL, null),
	special 				(FormatoMedia.ANIME, FormatoAnime.ESPECIAL, null),
	
	manga 			        (FormatoMedia.MANGA, null, null),
	mangabyMiwaUeda         (FormatoMedia.MANGA, null, null),
	mangabyR_Shimizu        (FormatoMedia.MANGA, null, null),
	mangabyKKawaguchi       (FormatoMedia.MANGA, null, null),
	mangabyEuclid           (FormatoMedia.MANGA, null, null),
	MangaUKOAV              (FormatoMedia.MANGA, null, null),
	mangabyK_Yasunaga       (FormatoMedia.MANGA, null, null),
	mangabyHiro             (FormatoMedia.MANGA, null, null),
	mangabyRakko            (FormatoMedia.MANGA, null, null),
	mangabyM_Kawasou        (FormatoMedia.MANGA, null, null),
	mangabyY_Kawahara       (FormatoMedia.MANGA, null, null),
	mangabyS_Koohara        (FormatoMedia.MANGA, null, null),
	mangabyNishiokaBS       (FormatoMedia.MANGA, null, null),
	mangabyRobinNishi       (FormatoMedia.MANGA, null, null),
	mangabyT_Fuji           (FormatoMedia.MANGA, null, null),
	mangabyA_Himekawa       (FormatoMedia.MANGA, null, null),
	mangabyJunFukami        (FormatoMedia.MANGA, null, null),
	mangabySabusuka         (FormatoMedia.MANGA, null, null),
	mangabyAkioTanaka       (FormatoMedia.MANGA, null, null),
	mangabyM_Yumeno         (FormatoMedia.MANGA, null, null),
	manga199598             (FormatoMedia.MANGA, null, null),
	mangaKazumaKodaka       (FormatoMedia.MANGA, null, null),
	movieseries             (FormatoMedia.MANGA, null, null),
	mangabyKShimamoto       (FormatoMedia.MANGA, null, null),
	mangabyA_Shiina         (FormatoMedia.MANGA, null, null),
	manga2011               (FormatoMedia.MANGA, null, null),
	mangabyMakiUsami        (FormatoMedia.MANGA, null, null),
	mangabyD_Hiyama         (FormatoMedia.MANGA, null, null),
	mangabyK_Minekura       (FormatoMedia.MANGA, null, null),
	mangabyT_Fujikawa       (FormatoMedia.MANGA, null, null),
	mangabyH_Amano          (FormatoMedia.MANGA, null, null),
	mangabyK_Okada          (FormatoMedia.MANGA, null, null),
	mangabyTomuOhmi         (FormatoMedia.MANGA, null, null),
	mangabyIshinomori       (FormatoMedia.MANGA, null, null),
	mangabySMizushiro       (FormatoMedia.MANGA, null, null),
	mangabyA_Katsu          (FormatoMedia.MANGA, null, null),
	mangabyAkiraGoto        (FormatoMedia.MANGA, null, null),
	mangabyK_Nananan        (FormatoMedia.MANGA, null, null),
	mangabyInomaru          (FormatoMedia.MANGA, null, null),
	mangabyF_Soryo          (FormatoMedia.MANGA, null, null),
	mangabyTakaoSaito       (FormatoMedia.MANGA, null, null),
	mangabyM_Iwase          (FormatoMedia.MANGA, null, null),
	mangabyAoMimori         (FormatoMedia.MANGA, null, null),
	mangabyH_Kino           (FormatoMedia.MANGA, null, null),
	mangabyN_Nakamura       (FormatoMedia.MANGA, null, null),
	mangabyT_Chiya          (FormatoMedia.MANGA, null, null),
	mangabyM_Yamada         (FormatoMedia.MANGA, null, null),
	mangabyYukiNakaji       (FormatoMedia.MANGA, null, null),
	manga21996              (FormatoMedia.MANGA, null, null),
	mangabyK_Tokita         (FormatoMedia.MANGA, null, null),
	mangabyT_Ishiki         (FormatoMedia.MANGA, null, null),
	mangaKitakataHa         (FormatoMedia.MANGA, null, null),
	mangaKarakarakemuri     (FormatoMedia.MANGA, null, null),
	mangabyA_Cagiva         (FormatoMedia.MANGA, null, null),
	manga2002               (FormatoMedia.MANGA, null, null),
	mangabynakedape         (FormatoMedia.MANGA, null, null),
	mangabyO_Ishiwata       (FormatoMedia.MANGA, null, null),
	mangaby17authors        (FormatoMedia.MANGA, null, null),
	mangabyY_Yokoyama       (FormatoMedia.MANGA, null, null),
	mangabyYokoKamio        (FormatoMedia.MANGA, null, null),
	mangabyShigematsu       (FormatoMedia.MANGA, null, null),
	mangabyKeiToume         (FormatoMedia.MANGA, null, null),
	mangabyK_Motomi         (FormatoMedia.MANGA, null, null),
	mangabyMamiIto          (FormatoMedia.MANGA, null, null),
	mangabyM_Takayama       (FormatoMedia.MANGA, null, null),
	mangabyR_Fukiyama       (FormatoMedia.MANGA, null, null),
	mangabyQtaMinami        (FormatoMedia.MANGA, null, null),
	mangabyS_Akane          (FormatoMedia.MANGA, null, null),
	manganonexistent        (FormatoMedia.MANGA, null, null),
	mangabySakurazawa       (FormatoMedia.MANGA, null, null),
	mangabyJ_Kagemaru       (FormatoMedia.MANGA, null, null),
	mangabyKubonouchi       (FormatoMedia.MANGA, null, null),
	mangabyYumiTamura       (FormatoMedia.MANGA, null, null),
	mangabyNHamaguchi       (FormatoMedia.MANGA, null, null),
	manga1994               (FormatoMedia.MANGA, null, null),
	mangabyA_Nanase         (FormatoMedia.MANGA, null, null),
	mangabyK_Senno          (FormatoMedia.MANGA, null, null),
	mangabyA_Kawaraya       (FormatoMedia.MANGA, null, null),
	mangabyM_Asakura        (FormatoMedia.MANGA, null, null),
	mangabyH_Ishimaru       (FormatoMedia.MANGA, null, null),
	mangabyM_Sugiyama       (FormatoMedia.MANGA, null, null),
	mangabyY_Kuritsu        (FormatoMedia.MANGA, null, null),
	mangabyK_Miura          (FormatoMedia.MANGA, null, null),
	mangabyLMatsumoto       (FormatoMedia.MANGA, null, null),
	mangabyY_Tatsumi        (FormatoMedia.MANGA, null, null),
	mangabyM_Orihara        (FormatoMedia.MANGA, null, null),
	manhwa                  (FormatoMedia.MANGA, null, null),
	mangabyKozueChiba       (FormatoMedia.MANGA, null, null),
	mangabyY_Yamamoto       (FormatoMedia.MANGA, null, null),
	manga1986               (FormatoMedia.MANGA, null, null),
	mangabyS_Inui           (FormatoMedia.MANGA, null, null),
	mangabyM_Yokoyama       (FormatoMedia.MANGA, null, null),
	mangabyTaneichi         (FormatoMedia.MANGA, null, null),
	mangabyY_Kuwabara       (FormatoMedia.MANGA, null, null),
	mangabyS_Hosoma         (FormatoMedia.MANGA, null, null),
	mangabyR_Minagawa       (FormatoMedia.MANGA, null, null),
	mangabyvarious          (FormatoMedia.MANGA, null, null),
	mangaYuaKotegawa        (FormatoMedia.MANGA, null, null),
	mangabyS_Furukawa       (FormatoMedia.MANGA, null, null),
	mangabyT_Hojo           (FormatoMedia.MANGA, null, null),
	mangabyL_Ichijo         (FormatoMedia.MANGA, null, null),
	mangabyAyumiKasai       (FormatoMedia.MANGA, null, null),
	mangabyUJin             (FormatoMedia.MANGA, null, null),
	mangabyS_Mikuriya       (FormatoMedia.MANGA, null, null),
	mangabyCLAMP            (FormatoMedia.MANGA, null, null),
	mangabyM_Shizaki        (FormatoMedia.MANGA, null, null),
	KoreanAmericanmanga     (FormatoMedia.MANGA, null, null),
	mangabyK_Okazaki        (FormatoMedia.MANGA, null, null),
	manga2                  (FormatoMedia.MANGA, null, null),
	mangabyMayukiAnan       (FormatoMedia.MANGA, null, null),
	mangabyK_Muraeda        (FormatoMedia.MANGA, null, null),
	mangabyKaoriYuki        (FormatoMedia.MANGA, null, null),
	mangabyAiYazawa         (FormatoMedia.MANGA, null, null),
	mangabyM_Mihara         (FormatoMedia.MANGA, null, null),
	KoreanFrenchmanga       (FormatoMedia.MANGA, null, null),
	mangabyJ_Matsumoto      (FormatoMedia.MANGA, null, null),
	mangabyK_Narita         (FormatoMedia.MANGA, null, null),
	mangabyS_Rokuya         (FormatoMedia.MANGA, null, null),
	mangabyO_Tezuka         (FormatoMedia.MANGA, null, null),
	mangabyYouHiguri        (FormatoMedia.MANGA, null, null),
	mangabyH_Sekiguchi      (FormatoMedia.MANGA, null, null),
	mangabyYukaTakase       (FormatoMedia.MANGA, null, null),
	mangabyChihoSaito       (FormatoMedia.MANGA, null, null),
	mangabyS_Ikezawa        (FormatoMedia.MANGA, null, null),
	mangabyYuzuhaOugi       (FormatoMedia.MANGA, null, null),
	mangabyHKobayashi       (FormatoMedia.MANGA, null, null),
	mangabyY_Tonogai        (FormatoMedia.MANGA, null, null),
	mangabyH_Yuzuki         (FormatoMedia.MANGA, null, null),
	manga19992005           (FormatoMedia.MANGA, null, null),
	mangabyAkiraHonma       (FormatoMedia.MANGA, null, null),
	mangabyA_Yamabuki       (FormatoMedia.MANGA, null, null),
	mangabyB_Terasawa       (FormatoMedia.MANGA, null, null),
	mangabyK_Izumi          (FormatoMedia.MANGA, null, null),
	mangabyEikiEiki         (FormatoMedia.MANGA, null, null),
	mangabyK_Hoshino        (FormatoMedia.MANGA, null, null),
	mangabyY_Hashida        (FormatoMedia.MANGA, null, null),
	mangabyRaTe             (FormatoMedia.MANGA, null, null),
	mangabyAkiMochida       (FormatoMedia.MANGA, null, null),
	mangabyK_Okamoto        (FormatoMedia.MANGA, null, null),
	mangabyTouiHasumi       (FormatoMedia.MANGA, null, null),
	mangabyN_Kuwata         (FormatoMedia.MANGA, null, null),
	mangabyT_Egawa          (FormatoMedia.MANGA, null, null),
	mangabyN_Chrono         (FormatoMedia.MANGA, null, null),
	mangabyT_Watanabe       (FormatoMedia.MANGA, null, null),
	mangabyA_Hanamaki       (FormatoMedia.MANGA, null, null),
	mangabyY_Kagesaki       (FormatoMedia.MANGA, null, null),
	webmanga                (FormatoMedia.MANGA, null, null),
	mangabyL_Nekojima       (FormatoMedia.MANGA, null, null),
	mangabyT_Hirakawa       (FormatoMedia.MANGA, null, null),
	mangabyKiaAsamiya       (FormatoMedia.MANGA, null, null),
	mangabyR_Kusakabe       (FormatoMedia.MANGA, null, null),
	mangabyU_Furuya         (FormatoMedia.MANGA, null, null),
	mangabyS_Sugita         (FormatoMedia.MANGA, null, null),
	mangabyKWatashiya       (FormatoMedia.MANGA, null, null),
	manga1960s              (FormatoMedia.MANGA, null, null),
	mangabyM_Asami          (FormatoMedia.MANGA, null, null),
	mangabyH_Taira          (FormatoMedia.MANGA, null, null),
	mangabyMonkeyPunch      (FormatoMedia.MANGA, null, null),
	mangabyK_Yabuki         (FormatoMedia.MANGA, null, null),
	mangabyTTakahashi       (FormatoMedia.MANGA, null, null),
	mangabyY_Iori           (FormatoMedia.MANGA, null, null),
	mangabyS_Seino          (FormatoMedia.MANGA, null, null),
	mangabyWYoshizumi       (FormatoMedia.MANGA, null, null),
	manga1990s              (FormatoMedia.MANGA, null, null),
	mangabyYMatsumoto       (FormatoMedia.MANGA, null, null),
	mangabyShimabukuro      (FormatoMedia.MANGA, null, null),
	mangabyK_Araki          (FormatoMedia.MANGA, null, null),
	mangabyKYoshimizu       (FormatoMedia.MANGA, null, null),
	mangabyYuuya            (FormatoMedia.MANGA, null, null),
	mangabyA_Soga           (FormatoMedia.MANGA, null, null),
	ResourceBook            (FormatoMedia.MANGA, null, null),
	mangabyM_Katsura        (FormatoMedia.MANGA, null, null),
	mangabyH_Toribito       (FormatoMedia.MANGA, null, null),
	mangabyM_Kawahara       (FormatoMedia.MANGA, null, null),
	mangabyTKawashima       (FormatoMedia.MANGA, null, null),
	mangabyKoujiSeo         (FormatoMedia.MANGA, null, null),
	mangabyR_Amazume        (FormatoMedia.MANGA, null, null),
	Taiwanesemanga	        (FormatoMedia.MANGA, null, null),
	animanga      	        (FormatoMedia.MANGA, null, null),
	worldmanga    	        (FormatoMedia.MANGA, null, null),
	U_S_manga     	        (FormatoMedia.MANGA, null, null),
	Chinesemanga 	        (FormatoMedia.MANGA, null, null),
	OELmanga      	        (FormatoMedia.MANGA, null, null),
	U_S_manga2    	        (FormatoMedia.MANGA, null, null),
	KoreanmangaSoYoungLee   (FormatoMedia.MANGA, null, null),
	ChinesemangabySuetChing (FormatoMedia.MANGA, null, null),
	mangaT_Noguchi          (FormatoMedia.MANGA, null, null),
	onlinecomic             (FormatoMedia.MANGA, null, null),
	manga22008              (FormatoMedia.MANGA, null, null),
	resourcebook            (FormatoMedia.MANGA, null, null),
	U_S_comic               (FormatoMedia.MANGA, null, null),
	mangabyR_Miyahara       (FormatoMedia.MANGA, null, null),
	mangabyR_Ikegami        (FormatoMedia.MANGA, null, null),
	mangaYoshida_Ueda       (FormatoMedia.MANGA, null, null),
	mangaNakabaSuzuki       (FormatoMedia.MANGA, null, null),
	mangabyT_Shimura        (FormatoMedia.MANGA, null, null),
	mangabyH_Madarame       (FormatoMedia.MANGA, null, null),
	mangabyAsukaEd_         (FormatoMedia.MANGA, null, null),
	mangabyK_Momoyuki       (FormatoMedia.MANGA, null, null),
	mangabyT_Noguchi        (FormatoMedia.MANGA, null, null),
	mangaM_Sakakibara       (FormatoMedia.MANGA, null, null),
	mangabyNaseYamato       (FormatoMedia.MANGA, null, null),
	mangabyT_Yoshimura      (FormatoMedia.MANGA, null, null),
	mangabyHarutoRyo        (FormatoMedia.MANGA, null, null),
	mangabyAoiIkebe         (FormatoMedia.MANGA, null, null),
	mangabyŌtoTaguchi       (FormatoMedia.MANGA, null, null),
	mangaKanaeHazuki        (FormatoMedia.MANGA, null, null),
	mangaRyoTakagi          (FormatoMedia.MANGA, null, null),
	mangaHitoriRenda        (FormatoMedia.MANGA, null, null),
	mangabyMAnagura         (FormatoMedia.MANGA, null, null),
	mangabyS_Tanaka         (FormatoMedia.MANGA, null, null),
	mangaS_Tsuzuki          (FormatoMedia.MANGA, null, null),
	mangabyT_Yamada         (FormatoMedia.MANGA, null, null),
	mangabyY_Ozaki          (FormatoMedia.MANGA, null, null),
	mangabyH_Arashima       (FormatoMedia.MANGA, null, null),
	mangabyYuijiAniya       (FormatoMedia.MANGA, null, null),
	mangabyHoruri           (FormatoMedia.MANGA, null, null),
	mangabyPirontan         (FormatoMedia.MANGA, null, null),
	mangaHiroKiyohara       (FormatoMedia.MANGA, null, null),
	mangabyToshikiYui       (FormatoMedia.MANGA, null, null),
	mangabyRyoIkuemi        (FormatoMedia.MANGA, null, null),
	mangabyGuranyuto        (FormatoMedia.MANGA, null, null),
	mangabyKozueAmano       (FormatoMedia.MANGA, null, null),
	mangabytosh             (FormatoMedia.MANGA, null, null),
	mangabyMunko            (FormatoMedia.MANGA, null, null),
	mangabyS_Akira          (FormatoMedia.MANGA, null, null),
	mangabyKojikiOji        (FormatoMedia.MANGA, null, null),
	mangaM_Kaneshiro        (FormatoMedia.MANGA, null, null),
	mangaHiroMadarame       (FormatoMedia.MANGA, null, null),
	mangaN_Tsukudani        (FormatoMedia.MANGA, null, null),
	mangabyYukizoSaku       (FormatoMedia.MANGA, null, null),
	mangabyShouTajima       (FormatoMedia.MANGA, null, null),
	mangabyKozoOmori        (FormatoMedia.MANGA, null, null),
	picturebook             (FormatoMedia.MANGA, null, null),
	lightnovel			    (FormatoMedia.MANGA, null, null),
	mangabyOtoTaguchi	    (FormatoMedia.MANGA, null, null),
	mangaNaoEmoto           (FormatoMedia.MANGA, null, null),
	mangaK_UchiUchi         (FormatoMedia.MANGA, null, null),
	mangaAoiHiiragi         (FormatoMedia.MANGA, null, null),
	mangaY_Yasumura         (FormatoMedia.MANGA, null, null),
	mangaFumikoFumi         (FormatoMedia.MANGA, null, null),
	mangaS_Tsuchiyama       (FormatoMedia.MANGA, null, null),
	mangaMamiyaOki          (FormatoMedia.MANGA, null, null),
	mangaAyuWatanabe        (FormatoMedia.MANGA, null, null),
	mangaYukiNakaji         (FormatoMedia.MANGA, null, null),
	mangaMinamiMizuno       (FormatoMedia.MANGA, null, null),
	mangaMotoHagio          (FormatoMedia.MANGA, null, null),
	mangaK_Muraeda          (FormatoMedia.MANGA, null, null),
	mangaAkimiYoshida       (FormatoMedia.MANGA, null, null),
	ChinesemangaYanshuYu    (FormatoMedia.MANGA, null, null),
	mangaSanaeRokuya        (FormatoMedia.MANGA, null, null),
	mangaKenjiTsuruta       (FormatoMedia.MANGA, null, null),
	mangaSutaroHanao        (FormatoMedia.MANGA, null, null),
	
	movie 				   (FormatoMedia.FILME, null, null),
	movie3D2010            (FormatoMedia.FILME, null, null),
	movie1                 (FormatoMedia.FILME, null, null),
	liveaction3Dmovie      (FormatoMedia.FILME, null, null),
	cancelledCGmovie       (FormatoMedia.FILME, null, null),
	movie2                 (FormatoMedia.FILME, null, null),
	movie3                 (FormatoMedia.FILME, null, null),
	movie4                 (FormatoMedia.FILME, null, null),
	movie5                 (FormatoMedia.FILME, null, null),
	movie1999              (FormatoMedia.FILME, null, null),
	movie6                 (FormatoMedia.FILME, null, null),
	movie7                 (FormatoMedia.FILME, null, null),
	movie8                 (FormatoMedia.FILME, null, null),
	movie9                 (FormatoMedia.FILME, null, null),
	movie1997              (FormatoMedia.FILME, null, null),
	movie1994              (FormatoMedia.FILME, null, null),
	cancelledmovie         (FormatoMedia.FILME, null, null),
	movie20                (FormatoMedia.FILME, null, null),
	USliveactionmovie      (FormatoMedia.FILME, null, null),
	movie11                (FormatoMedia.FILME, null, null),
	movie12                (FormatoMedia.FILME, null, null),
	movie13                (FormatoMedia.FILME, null, null),
	movie14                (FormatoMedia.FILME, null, null),
	movie15                (FormatoMedia.FILME, null, null),
	movie16                (FormatoMedia.FILME, null, null),
	movie17                (FormatoMedia.FILME, null, null),
	movie18                (FormatoMedia.FILME, null, null),
	movie19                (FormatoMedia.FILME, null, null),
	liveactionmovie        (FormatoMedia.FILME, null, null),
	U_S_movie              (FormatoMedia.FILME, null, null),
	movie2012              (FormatoMedia.FILME, null, null),
	movie2009              (FormatoMedia.FILME, null, null),
	movieOsamuTezuka       (FormatoMedia.FILME, null, null),
	U_S_movieParody        (FormatoMedia.FILME, null, null),
	movie10                (FormatoMedia.FILME, null, null),
	movie1977              (FormatoMedia.FILME, null, null),
	USCGmovie              (FormatoMedia.FILME, null, null),
	moviebySatoshiKon      (FormatoMedia.FILME, null, null),
	movies                 (FormatoMedia.FILME, null, null),
	moviebyO_Tezuka        (FormatoMedia.FILME, null, null),
	liveactionmovie2001    (FormatoMedia.FILME, null, null),
	hybridmovie            (FormatoMedia.FILME, null, null),
	liveactionmovie1978    (FormatoMedia.FILME, null, null),
	liveactionmovie1973    (FormatoMedia.FILME, null, null),
	movie1966              (FormatoMedia.FILME, null, null),
	moviesegment           (FormatoMedia.FILME, null, null),
	movieakaWindaria       (FormatoMedia.FILME, null, null),
	liveactionmoviespecial (FormatoMedia.FILME, null, null),
	stalledmovie           (FormatoMedia.FILME, null, null),
	Koreanmovie            (FormatoMedia.FILME, null, null),
	Chinesemovie 		   (FormatoMedia.FILME, null, null),
	liveactionmovie2002    (FormatoMedia.FILME, null, null),
	liveactionmovie2005    (FormatoMedia.FILME, null, null),
	movie21                (FormatoMedia.FILME, null, null),
	cancelledlivemovie2006 (FormatoMedia.FILME, null, null),
	movie22                (FormatoMedia.FILME, null, null),
	movie23                (FormatoMedia.FILME, null, null),
	movie2016              (FormatoMedia.FILME, null, null),
	OAVmovie               (FormatoMedia.FILME, null, null),
	USmovie                (FormatoMedia.FILME, null, null),
	movieK_Kawamoto        (FormatoMedia.FILME, null, null),
	movieR_Kinoshita       (FormatoMedia.FILME, null, null),
	cancelledlivemovie     (FormatoMedia.FILME, null, null),
	movie1993              (FormatoMedia.FILME, null, null),
	
	liveactionTVdrama	   (FormatoMedia.DORAMA, null, FormatoDorama.JDRAMA),
	liveactionOAVdrama	   (FormatoMedia.DORAMA, null, FormatoDorama.JDRAMA),
	liveactionspecial	   (FormatoMedia.DORAMA, null, FormatoDorama.JDRAMA),
	liveaction	  		   (FormatoMedia.DORAMA, null, FormatoDorama.JDRAMA),
	liveactionSpecial	   (FormatoMedia.DORAMA, null, FormatoDorama.JDRAMA),
	liveactionmovieseries  (FormatoMedia.DORAMA, null, FormatoDorama.JDRAMA),
	liveactionONA          (FormatoMedia.DORAMA, null, FormatoDorama.JDRAMA),
	liveactionmovie2014    (FormatoMedia.DORAMA, null, FormatoDorama.JDRAMA),
	CDDrama                (FormatoMedia.DORAMA, null, FormatoDorama.JDRAMA),
	liveactionOAV    	   (FormatoMedia.DORAMA, null, FormatoDorama.JDRAMA),
	liveactionTVmovie      (FormatoMedia.DORAMA, null, FormatoDorama.JDRAMA),
	liveactionTV3          (FormatoMedia.DORAMA, null, FormatoDorama.JDRAMA),
	liveactionTV2          (FormatoMedia.DORAMA, null, FormatoDorama.JDRAMA),
	liveactionTV2004       (FormatoMedia.DORAMA, null, FormatoDorama.JDRAMA),
	;
	
	private FormatoMedia formatoMedia;
	private FormatoAnime formatoAnime;
	private FormatoDorama formatoDorama;

	/**
	 * @param formatoMedia
	 * @param formatoAnime
	 * @param formatoDorama
	 */
	private FormatoANN(FormatoMedia formatoMedia, FormatoAnime formatoAnime, FormatoDorama formatoDorama) {
		this.formatoMedia = formatoMedia;
		this.formatoAnime = formatoAnime;
		this.formatoDorama = formatoDorama;
	}

	/**
	 * @return the formatoMedia
	 */
	public FormatoMedia getFormatoMedia() {
		return formatoMedia;
	}

	/**
	 * @param formatoMedia the formatoMedia to set
	 */
	public void setFormatoMedia(FormatoMedia formatoMedia) {
		this.formatoMedia = formatoMedia;
	}

	/**
	 * @return the formatoAnime
	 */
	public FormatoAnime getFormatoAnime() {
		return formatoAnime;
	}

	/**
	 * @param formatoAnime the formatoAnime to set
	 */
	public void setFormatoAnime(FormatoAnime formatoAnime) {
		this.formatoAnime = formatoAnime;
	}

	/**
	 * @return the formatoDorama
	 */
	public FormatoDorama getFormatoDorama() {
		return formatoDorama;
	}

	/**
	 * @param formatoDorama the formatoDorama to set
	 */
	public void setFormatoDorama(FormatoDorama formatoDorama) {
		this.formatoDorama = formatoDorama;
	}
}
